add composer.json
weglot/languages pull request #43
Opened 2024-01-08 10:58 UTC by glx77

L'idée c'est d'ajouter un composer.json pour que je puisse ajouter le repo languages comme une dépendence php (vendor)

2024-01-09 16:05 UTC, floranpagliai requested changes

2024-01-10 13:16 UTC, VincentLanglet reviewed
Je pense qu'il faut mettre en place un autoload PSR-4. Du genre
```
"autoload": {
        "psr-4": {
            "WeglotLanguages\\": "dist/",
        }
    },
```

cf 
https://github.com/weglot/weglot-php/blob/develop/composer.json#L57-L62

Et changer les namespaces des classes
https://github.com/weglot/languages/blob/imporvement/add-composer-json/dist/Languages.php#L3
https://github.com/weglot/languages/blob/imporvement/add-composer-json/dist/Countries.php#L3

En `namespace WeglotLanguages`

Ca nécessitera un changement lors du prochain bump coté core mais:
- On aura plus besoin de déclarer l'autoload dans le composer.json si on install via php
- Y aura plus d'erreur phpstorm sur cette lib vis à vis du namespace qui respecte pas le psr.

A tester...

2024-01-10 16:32 UTC, glx77 commented
> Je pense qu'il faut mettre en place un autoload PSR-4. Du genre
> 
> ```
> "autoload": {
>         "psr-4": {
>             "WeglotLanguages\\": "dist/",
>         }
>     },
> ```
> 
> cf https://github.com/weglot/weglot-php/blob/develop/composer.json#L57-L62
> 
> Et changer les namespaces des classes https://github.com/weglot/languages/blob/imporvement/add-composer-json/dist/Languages.php#L3 https://github.com/weglot/languages/blob/imporvement/add-composer-json/dist/Countries.php#L3
> 
> En `namespace WeglotLanguages`
> 
> Ca nécessitera un changement lors du prochain bump coté core mais:
> 
> * On aura plus besoin de déclarer l'autoload dans le composer.json si on install via php
> * Y aura plus d'erreur phpstorm sur cette lib vis à vis du namespace qui respecte pas le psr.
> 
> A tester...

Yes mais pour moi ses modifs sont à faire au niveau de la lib https://github.com/weglot/weglot-php pas de celle ci non ? @VincentLanglet

2024-01-10 16:44 UTC, VincentLanglet commented
> Yes mais pour moi ses modifs sont à faire au niveau de la lib [weglot/weglot-php](https://github.com/weglot/weglot-php) pas de celle ci non ? @VincentLanglet

C'est la lib PHP qui fournit son "mode d'installation".

Exemple, 
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/composer.json#L96-L100

Du coup pour moi, il faut:
- Dans le composer weglot/languages, mettre un truc du genre: 
```
"autoload": {
    "psr-4": {
        "WeglotLanguages\\": "dist/",
    }
},
```

- Changer les namespaces des classes Languages et Countries pour matcher le composer.

Ensuite, dans weglot/weglot-php, tu pourras:
- Installer la lib avec composer
- Virer cette ligne https://github.com/weglot/weglot-php/blob/develop/composer.json#L60 (L'install se fera toute seule !)

Si je comprend bien comment ça marche...

2024-01-11 14:38 UTC, VincentLanglet commented on composer.json
> +      "WeglotLanguages\\": "dist/"
Je pense qu'il faut également faire:
https://github.com/weglot/languages/blob/master/bin/populateLanguages.js#L10
en
```
"<?php\n\nnamespace WeglotLanguages;\n\nclass Languages\n{\n    const DATA = [\n"
```

et 

https://github.com/weglot/languages/blob/master/bin/populateLanguages.js#L32
en
```
"<?php\n\nnamespace WeglotLanguages;\n\nclass Countries\n{\n    const DATA = [\n"
```

Pour que les deux classes soient dans le namespace en question.

2024-01-11 15:13 UTC, glx77 commented on composer.json
> +      "WeglotLanguages\\": "dist/"
ha yes my bad, c'est fix

2024-01-11 15:19 UTC, VincentLanglet approved these changes

2024-01-11 16:15 UTC, floranpagliai requested changes

2024-01-11 16:15 UTC, floranpagliai commented on dist/Countries.php
> -namespace Countries;
Countries

2024-01-11 16:25 UTC, VincentLanglet commented on dist/Countries.php
> -namespace Countries;
En fait c'est pas cohérent @floranpagliai ; c'est un "défaut" qu'il y a depuis toujours sur le dossier dist.
C'est le nom de la classe qui est Countries, mais les deux classes devrait avoir le même namespace.

Une lib = Un composer.json = Un namespace.

D'ailleurs PHPStorm remonte un warning à ce sujet.

C'est mieux d'avoir un namespace unique (par exemple WeglotLanguages) et d'avoir deux classes qui seront:
```
WeglotLanguages/Languages
WeglotLanguages/Countries
```
sous le même namespace ; plutôt que de devoir gérer deux namespaces
```
Languages/Languages
Countries/Countries
```
qui:
- ont des noms garantissent pas l'unicité (on pourrait avoir un jour un conflit avec une autre lib)
- sous entendent que ce sont deux libs différentes

2024-01-11 16:26 UTC, floranpagliai commented on dist/Countries.php
> -namespace Countries;
Ah oui j'ai lu en travers j'ai cru que c'était le nom de la classe qui avait été rename par un copy/paste malheureux

2024-01-23 13:50 UTC, merged